ALTER TABLE USRK
CHANGE COLUMN USR_CPFJ USR_CNPJ VARCHAR(14) NOT NULL;

ALTER TABLE USRK
ADD COLUMN USR_FANT VARCHAR(150) AFTER USR_NAME,
ADD COLUMN USR_DATA_FUND DATE AFTER USR_CNPJ,
ADD COLUMN USR_SITUACAO VARCHAR(50) AFTER USR_DATA_FUND,
ADD COLUMN USR_SITE VARCHAR(255) AFTER USR_SITUACAO,

ADD COLUMN USR_CEP VARCHAR(8) AFTER USR_SITE,
ADD COLUMN USR_LOGR VARCHAR(150) AFTER USR_CEP,
ADD COLUMN USR_NUM VARCHAR(10) AFTER USR_LOGR,
ADD COLUMN USR_COMPL VARCHAR(100) AFTER USR_NUM,
ADD COLUMN USR_BAIRRO VARCHAR(100) AFTER USR_COMPL,
ADD COLUMN USR_CIDADE VARCHAR(100) AFTER USR_BAIRRO,
ADD COLUMN USR_ESTADO CHAR(2) AFTER USR_CIDADE,

ADD COLUMN USR_TEL VARCHAR(20) AFTER USR_ESTADO,
ADD COLUMN USR_CEL VARCHAR(20) AFTER USR_TEL,

ADD COLUMN USR_RESP VARCHAR(150) AFTER USR_CEL;