CREATE DATABASE SistemaAdm
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE SistemaAdm;

CREATE TABLE USRK (
    USR_AIC INT NOT NULL AUTO_INCREMENT,
    USR_NAME VARCHAR(150) NOT NULL,
    USR_PASS VARCHAR(255) NOT NULL,
    USR_EML VARCHAR(150) NOT NULL,
    USR_CPFJ VARCHAR(14) NOT NULL,
    USR_ATV BOOLEAN NOT NULL DEFAULT 0,
    USR_CAD_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (USR_AIC),
    UNIQUE KEY UK_USR_EML (USR_EML),
    UNIQUE KEY UK_USR_CPFJ (USR_CPFJ)

) ENGINE=InnoDB;

CREATE TABLE AUDIT (
    AUT_AIC INT NOT NULL AUTO_INCREMENT,
    USR_AIC INT NOT NULL,
    AUT_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    AUT_IP VARCHAR(45),
    AUT_DISPO VARCHAR(150),
    AUT_STATUS BOOLEAN NOT NULL DEFAULT 0,

    PRIMARY KEY (AUT_AIC),

    INDEX IDX_AUDIT_USR (USR_AIC),

    CONSTRAINT FK_AUDIT_USRK
        FOREIGN KEY (USR_AIC)
        REFERENCES USRK(USR_AIC)

) ENGINE=InnoDB;