CREATE DATABSE SistemaAdm;
CHARACTER SET utf8mb4;
COLLATE utf8mb4_unicode_ci;

USE SistemaAdm

CREATE TABLE usuarios {
    USR_AIC INT NOT NULL AUTO_INCREMENT,
    USR_NAME VARCHAR(150) NOT NULL,
    USR_PASS VARCHAR(150) NOT NULL,
    USR_EML VARCHAR(150) NOT NULL,
    USR_CPJ CHAR(14) NOT NULL,
    USR_ATV BOOLEAN NOT NULL DEFAULT 0,
    USR_CAD_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    PRIMARY KEY (USR_AIC),
    UNIQUE KEY (UST_EML),
    UNIQUE KEY (USR_CPF)
};

CREATE TABLE auditoria{
    AUT_AIC INT NOT NULL AUTO_INCREMENT,
    USR_AIC INT NOT NULL,
    USR_LG_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USR_LG_IP VARCHAR(45),
    USR_LG_DISPO VARCHAR(150) NULL,
    USR_LG_ATV BOOLEAN NOT NULL DEFAULT 0,

    PRIMARY KEY (AUT_AIC),

    CONSTRAINT FK_auditoriaLogin_usuarios
        FOREIGN KEY (USR_AIC)
        REFERENCES  usuarios(USR_AIC)
};